### ISSUE TITLE
Есть ли какой либо вариант, чтобы не подключать модуль или не отправлять запросы к базе MySQL, если разрешение экрана пользователя сайта меньше чем заданное?

### ISSUE THREAD

**Issue by 8PandaPanda8** [dle-modules/DLE-BlockPro#147]
Очень важно для адаптивных сайтов. Иначе тратим ресурсы сервера в пустую. Вариант использовать мобильную версию от DLE не продуктивен и стар по своей философии.

**Comment by Yuribtr** [comment]
На этапе выполнения php скрипта движок сайта не знает ничего о разрешении экрана. Есть только информация о UserAgent. Таким образом вряд ли это можно сделать так как вы хотите. 
Гораздо надежнее в шаблоне smartphone просто не загружать модуль. Чем этот вариант вам плох - не пойму.

**Comment by tcse** [comment]
Все проще.Оберните строку подключения модуля в теги smartphone] текст [/smartphone] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт с мобильного телефона. [not-smartphone] текст [/not-smartphone] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт не с мобильного телефона. [tablet] текст [/tablet] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт с планшета. [not-tablet] текст [/not-tablet] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт не с планшета. [desktop] текст [/desktop] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт со стационарного компьютера или ноутбука. [not-desktop] текст [/not-desktop] будет выводить текст заключенный в теги, если посетитель просматривает ваш сайт не со стационарного компьютера или ноутбука.С уважением, Виталий ЧуяковСпециалист веб-студии TCSE.
-------- Исходное сообщение --------От: Yuri <notifications@github.com> Дата: 06.02.2019  20:51  (GMT+03:00) Кому: dle-modules/DLE-BlockPro <DLE-BlockPro@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: Re: [dle-modules/DLE-BlockPro] Есть ли какой либо вариант, чтобы не подключать модуль или не отправлять запросы к базе MySQL, если разрешение экрана пользователя сайта меньше чем заданное? (#147) На этапе выполнения php скрипта движок сайта не знает ничего о разрешении экрана. Есть только информация о UserAgent. Таким образом вряд ли это можно сделать так как вы хотите.
Гораздо надежнее в шаблоне smartphone просто не загружать модуль. Чем этот вариант вам плох - не пойму.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dle-modules/DLE-BlockPro","title":"dle-modules/DLE-BlockPro","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dle-modules/DLE-BlockPro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Yuribtr in #147: На этапе выполнения php скрипта движок сайта не знает ничего о разрешении экрана. Есть только информация о UserAgent. Таким образом вряд ли это можно сделать так как вы хотите. \r\nГораздо надежнее в шаблоне smartphone просто не загружать модуль. Чем этот вариант вам плох - не пойму."}],"action":{"name":"View Issue","url":"https://github.com/dle-modules/DLE-BlockPro/issues/147#issuecomment-461119859"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dle-modules/DLE-BlockPro/issues/147#issuecomment-461119859",
"url": "https://github.com/dle-modules/DLE-BlockPro/issues/147#issuecomment-461119859",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 8PandaPanda8** [comment]
Спасибо!
